server:
  port: 8080

spring:
  application:
    name: file

  config:
    use-legacy-processing: true

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  cloud:
    stream:
      kafka:
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde

      bindings:
        event-in:
          group: file
          destination: musicStreaming
          contentType: application/json
        event-out:
          destination: musicStreaming
          contentType: application/json

logging:
  level:
    root: WARN
    musicStreaming.file.custom: DEBUG

---

spring:
  profiles: host
  cloud.stream.kafka.binder.brokers: localhost:9092

server.port: 8084

---

spring:
  profiles: docker
  cloud.stream.kafka.binder.brokers: host.docker.internal:9092

---

spring:
  profiles: kubernates
  cloud.stream.kafka.binder.brokers: my-kafka:9092
