server:
  port: 8088

spring:
  application:
    name: gateway

  config:
    use-legacy-processing: true

  main.allow-bean-definition-overriding: true

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"

logging:
  level:
    root: WARN
    musicStreaming.gateway.custom: DEBUG

# JWT 설정 및 인증을 위한 Public & Private 키 경로
jwt:
  issuer: musicStreaming.io
  expire-after-seconds: 36000
  public.key: classpath:rsa.public.key

---

spring:
  profiles: host

  cloud:
    gateway:
      routes:
        - id: userAuthCheck
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/sanityCheck/authenticationCheck
            - Method=GET
          filters:
            - RewritePath=/api/user/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        - id: userChangeName
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/users/updateName
            - Method=PUT
          filters:
            - RewritePath=/api/user/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        - id: user
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/(?<segment>.*), /${segment}


        - id: musicNoAuth
          uri: http://localhost:8083
          predicates:
            - Path=/api/music/sanityCheck
            - Method=GET
          filters:
            - RewritePath=/api/music/(?<segment>.*), /${segment}

        - id: musicRequireAuth
          uri: http://localhost:8083
          predicates:
            - Path=/api/music/**
          filters:
            - RewritePath=/api/music/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter


        - id: fileSanityCheck
          uri: http://localhost:8084
          predicates:
            - Path=/api/file/sanityCheck
            - Method=GET
          filters:
            - RewritePath=/api/file/(?<segment>.*), /${segment}

        - id: fileResource
          uri: http://localhost:8084
          predicates:
            - Path=/api/file/**
          filters:
            - RewritePath=/api/file/(?<segment>.*), /resources/${segment}


        - id: playListNoAuth
          uri: http://localhost:8085
          predicates:
            - Path=/api/playList/sanityCheck
            - Method=GET
          filters:
            - RewritePath=/api/playList/(?<segment>.*), /${segment}

        - id: playListRequireAuth
          uri: http://localhost:8085
          predicates:
            - Path=/api/playList/**
          filters:
            - RewritePath=/api/playList/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter


        - id: commentNoAuth
          uri: http://localhost:8086
          predicates:
            - Path=/api/comment/sanityCheck
            - Method=GET
          filters:
            - RewritePath=/api/comment/(?<segment>.*), /${segment}

        - id: commentRequireAuth
          uri: http://localhost:8086
          predicates:
            - Path=/api/comment/**
          filters:
            - RewritePath=/api/comment/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter


        - id: collectedDataNoAuth
          uri: http://localhost:8087
          predicates:
            - Path=/api/collectedData/sanityCheck,/api/collectedData/users,/api/collectedData/musics,/api/collectedData/files,/api/collectedData/playLists,/api/collectedData/playListMusics,/api/collectedData/comments
            - Method=GET
          filters:
            - RewritePath=/api/collectedData/(?<segment>.*), /${segment}

        - id: collectedDataRequireAuth
          uri: http://localhost:8087
          predicates:
            - Path=/api/collectedData/**
          filters:
            - RewritePath=/api/collectedData/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter


        - id: frontend
          uri: http://localhost:3000
          predicates:
            - Path=/**

---

spring:
  profiles: docker

  cloud:
    gateway:
      routes:
        - id: userAuthCheck
          uri: http://host.docker.internal:8082
          predicates:
            - Path=/api/user/sanityCheck/authenticationCheck
            - Method=GET
          filters:
            - RewritePath=/api/user/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        - id: userChangeName
          uri: http://host.docker.internal:8082
          predicates:
            - Path=/api/user/users/updateName
            - Method=PUT
          filters:
            - RewritePath=/api/user/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        - id: user
          uri: http://host.docker.internal:8082
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/(?<segment>.*), /${segment}


        - id: musicNoAuth
          uri: http://host.docker.internal:8083
          predicates:
            - Path=/api/music/sanityCheck
            - Method=GET
          filters:
            - RewritePath=/api/music/(?<segment>.*), /${segment}

        - id: musicRequireAuth
          uri: http://host.docker.internal:8083
          predicates:
            - Path=/api/music/**
          filters:
            - RewritePath=/api/music/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter


        - id: fileSanityCheck
          uri: http://host.docker.internal:8084
          predicates:
            - Path=/api/file/sanityCheck
            - Method=GET
          filters:
            - RewritePath=/api/file/(?<segment>.*), /${segment}

        - id: fileResource
          uri: http://host.docker.internal:8084
          predicates:
            - Path=/api/file/**
          filters:
            - RewritePath=/api/file/(?<segment>.*), /resources/${segment}


        - id: playListNoAuth
          uri: http://host.docker.internal:8085
          predicates:
            - Path=/api/playList/sanityCheck
            - Method=GET
          filters:
            - RewritePath=/api/playList/(?<segment>.*), /${segment}

        - id: playListRequireAuth
          uri: http://host.docker.internal:8085
          predicates:
            - Path=/api/playList/**
          filters:
            - RewritePath=/api/playList/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter


        - id: commentNoAuth
          uri: http://host.docker.internal:8086
          predicates:
            - Path=/api/comment/sanityCheck
            - Method=GET
          filters:
            - RewritePath=/api/comment/(?<segment>.*), /${segment}

        - id: commentRequireAuth
          uri: http://host.docker.internal:8086
          predicates:
            - Path=/api/comment/**
          filters:
            - RewritePath=/api/comment/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter


        - id: collectedDataNoAuth
          uri: http://host.docker.internal:8087
          predicates:
            - Path=/api/collectedData/sanityCheck,/api/collectedData/users,/api/collectedData/musics,/api/collectedData/files,/api/collectedData/playLists,/api/collectedData/playListMusics,/api/collectedData/comments
            - Method=GET
          filters:
            - RewritePath=/api/collectedData/(?<segment>.*), /${segment}

        - id: collectedDataRequireAuth
          uri: http://host.docker.internal:8087
          predicates:
            - Path=/api/collectedData/**
          filters:
            - RewritePath=/api/collectedData/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter


        - id: frontend
          uri: http://host.docker.internal:3000
          predicates:
            - Path=/**

---

spring:
  profiles: kubernates

  cloud:
    gateway:
      routes:
        - id: userAuthCheck
          uri: http://user:8080
          predicates:
            - Path=/api/user/sanityCheck/authenticationCheck
            - Method=GET
          filters:
            - RewritePath=/api/user/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        - id: userChangeName
          uri: http://user:8080
          predicates:
            - Path=/api/user/users/updateName
            - Method=PUT
          filters:
            - RewritePath=/api/user/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        - id: user
          uri: http://user:8080
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/(?<segment>.*), /${segment}


        - id: musicNoAuth
          uri: http://music:8080
          predicates:
            - Path=/api/music/sanityCheck
            - Method=GET
          filters:
            - RewritePath=/api/music/(?<segment>.*), /${segment}

        - id: musicRequireAuth
          uri: http://music:8080
          predicates:
            - Path=/api/music/**
          filters:
            - RewritePath=/api/music/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter


        - id: fileSanityCheck
          uri: http://file:8080
          predicates:
            - Path=/api/file/sanityCheck
            - Method=GET
          filters:
            - RewritePath=/api/file/(?<segment>.*), /${segment}

        - id: fileResource
          uri: http://file:8080
          predicates:
            - Path=/api/file/**
          filters:
            - RewritePath=/api/file/(?<segment>.*), /resources/${segment}


        - id: playListNoAuth
          uri: http://play-list:8080
          predicates:
            - Path=/api/playList/sanityCheck
            - Method=GET
          filters:
            - RewritePath=/api/playList/(?<segment>.*), /${segment}

        - id: playListRequireAuth
          uri: http://play-list:8080
          predicates:
            - Path=/api/playList/**
          filters:
            - RewritePath=/api/playList/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter


        - id: commentNoAuth
          uri: http://comment:8080
          predicates:
            - Path=/api/comment/sanityCheck
            - Method=GET
          filters:
            - RewritePath=/api/comment/(?<segment>.*), /${segment}

        - id: commentRequireAuth
          uri: http://comment:8080
          predicates:
            - Path=/api/comment/**
          filters:
            - RewritePath=/api/comment/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter


        - id: collectedDataNoAuth
          uri: http://collected-data:8080
          predicates:
            - Path=/api/collectedData/sanityCheck,/api/collectedData/users,/api/collectedData/musics,/api/collectedData/files,/api/collectedData/playLists,/api/collectedData/playListMusics,/api/collectedData/comments
            - Method=GET
          filters:
            - RewritePath=/api/collectedData/(?<segment>.*), /${segment}

        - id: collectedDataRequireAuth
          uri: http://collected-data:8080
          predicates:
            - Path=/api/collectedData/**
          filters:
            - RewritePath=/api/collectedData/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter


        - id: frontend
          uri: http://frontend:3000
          predicates:
            - Path=/**